config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/users/search' => 'users#search'
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/books/search' => 'books#search'
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'message/:id' => 'messages#show', as: 'message'
  resources :messages, only: [:create, :index]
  delete 'notification/destroy_all' => 'notifications#destroy_all', as: 'notification'
  resources :notifications, only: :index
end

#書く順番気をつける

app/models/relationship.rb
class Relationship < ApplicationRecord
 belongs_to :follower, class_name: "User"
 belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  before_action :authenticate_user!
  
  def create
    current_user.follow(params[:user_id])
    @user = User.find(params[:user_id])
    @user.create_notification_follow(current_user)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
  end

  def followings
     user = User.find(params[:user_id])
     @users = user.followings
  end

  def followers
     user = User.find(params[:user_id])
     @users = user.followers
  end
  
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow-btn-index.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-primary" %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success" %>
<% end %>

app/views/relationships/_follow-btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-primary" %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success" %>
<% end %>

app/views/relationships/_follow-count.html.erb
フォロー数:
<%= link_to user_followings_path(user) do %>
  <%= user.followings.count %>
<% end %>
フォロワー数:
<%= link_to user_followers_path(user) do %>
  <%= user.followers.count %>
<% end %>

app/views/relationships/create.js.erb
$("#user_<%= @user.id %> .follow-count").html("<%= j(render 'relationships/follow-count', user: @user) %>");
$("#user_<%= @user.id %> .follow-btn").html("<%= j(render 'relationships/follow-btn', user: @user) %>");
$("#users_<%= @user.id %> .follow-btn-index").html("<%= j(render 'relationships/follow-btn-index', user: @user) %>");

app/views/relationships/destroy.js.erb
$("#user_<%= @user.id %> .follow-count").html("<%= j(render 'relationships/follow-count', user: @user) %>");
$("#user_<%= @user.id %> .follow-btn").html("<%= j(render 'relationships/follow-btn', user: @user) %>");
$("#users_<%= @user.id %> .follow-btn-index").html("<%= j(render 'relationships/follow-btn-index', user: @user) %>");

app/views/relationships/followers.html.erb
<div class="relationship-lists">
  <h1 class="mt-5 mb-5">フォロワー</h1>
  <% if @users.exists? %>
    <table class='table'>
      <thead class='thead'>
        <tr>
          <th>プロフィール画像</th>
          <th>ニックネーム</th>
          <th>自己紹介文</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <% if user.image? %>
                <%= image_tag user.image.url, class: "icon_image" %>
              <% else %>
                <%= image_tag "default.png", class: "icon_image" %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= user.introduction %></td>
            <td>
              <% if current_user != user %>
                <div id="users_<%= user.id %>">
                  <div class="follow-btn-index">
                    <%= render "relationships/follow-btn-index", user: user %>
                  </div>
                </div>
              <% end %>
            </td>
            <td><%= link_to '本棚を見る', user_path(user), class: "btn btn-secondary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
 <% else %>
   <div class="none">フォロワーはいません</div>
 <% end %>
</div>

app/views/relationships/followings.html.erb
<div class="relationship-lists">
  <h1 class="mt-5 mb-5">フォロー中</h1>
  <% if @users.exists? %>
    <table class='table'>
      <thead class='thead'>
        <tr>
          <th>プロフィール画像</th>
          <th>ニックネーム</th>
          <th>自己紹介文</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <% if user.image? %>
                <%= image_tag user.image.url, class: "icon_image" %>
              <% else %>
                <%= image_tag "default.png", class: "icon_image" %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td><%= user.introduction %></td>
            <td>
              <% if current_user != user %>
                <div id="users_<%= user.id %>">
                  <div class="follow-btn-index">
                    <%= render "relationships/follow-btn-index", user: user %>
                  </div>
                </div>
              <% end %>
            </td>
            <td><%= link_to '本棚を見る', user_path(user), class: "btn btn-secondary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="none">フォロー中のユーザーはいません</div>
  <% end %>
</div>