config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/users/search' => 'users#search'
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/books/search' => 'books#search'
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'message/:id' => 'messages#show', as: 'message'
  resources :messages, only: [:create, :index]
  delete 'notification/destroy_all' => 'notifications#destroy_all', as: 'notification'
  resources :notifications, only: :index
end

#書く順番気をつける

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :book, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_action :authenticate_user!

  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    #通知を全削除
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
      @visitor = notification.visitor
      @comment = nil
      your_item = link_to 'あなたの投稿', book_path(notification), style:"font-weight: bold;"
      @visitor_comment = notification.comment_id
      #notification.actionがfollowかlikeかcommentか
      case notification.action
        when "follow" then
          tag.a(notification.visitor.name, href:user_path(@visitor), style:"font-weight: bold;")+"があなたをフォローしました"
        when "favorite" then
          tag.a(notification.visitor.name, href:user_path(@visitor), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:book_path(notification.book_id), style:"font-weight: bold;")+"にいいねしました"
        when "comment" then
            @comment = Comment.find_by(id: @visitor_comment)&.comment
            tag.a(@visitor.name, href:user_path(@visitor), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:book_path(notification.book_id), style:"font-weight: bold;")+"にコメントしました"
      end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end

end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% book = notification.book %>
<div class="user-view clearfix">
  <%= link_to user_path(notification.visitor) do %>
    <% if visitor.image? %>
      <%= image_tag visitor.image.url, class: "icon_mini" %>
    <% else %>
      <%= image_tag "default.png", class: "icon_mini" %>
    <% end %>
  <% end %>
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span><br>
  <% if !@comment.nil? %>
    <p class="moderate-font text-center" style="color: #787878;"><%= @comment %></p>
  <% end %>
  <hr>
</div>

app/views/notifications/index.html.erb
<div class="notification">
  <h3 class="text-center">通知</h3>
  <%= link_to notification_path, method: :delete do %>
    <i class="fas fa-trash" style="color: black;"></i>
     <h7 style="color: black;">全削除</h7>
  <% end %>
  <hr>
  <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
  <% if notifications.exists? %>
    <div class="users-index">
      <%= render notifications %>
    </div>
  <% else %>
    <div class="none">通知はありません</div>
  <% end %>
</div>