config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/users/search' => 'users#search'
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/books/search' => 'books#search'
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'message/:id' => 'messages#show', as: 'message'
  resources :messages, only: [:create, :index]
  delete 'notification/destroy_all' => 'notifications#destroy_all', as: 'notification'
  resources :notifications, only: :index
end

#書く順番気をつける

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: { in: 1..15 }
  validates :introduction, length: { maximum: 160 }

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  # 自分からの通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 相手からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # プロフィール画像アップロード
  mount_uploader :image, ImageUploader

  # ユーザー検索用のメソッド
  def self.search(content)
    if content.present?
      User.where('name LIKE ?', '%'+content+'%')
    else
      []
    end
  end
  # フォローするメソッド
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すメソッド
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしてるかどうか判定
  def following?(user)
    followings.include?(user)
  end

  # フォローの通知
  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    # フォローされていない場合のみ通知を作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
    end
  end

  # アカウント作成時にメールを送信
  after_create :send_welcome_mail
  def send_welcome_mail
    ThanksMailer.send_signup_email(self).deliver
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def new_guest
    user = User.guest
    sign_in user
    flash[:primary] = 'ゲストユーザーとしてログインしました'
    redirect_to user_path(current_user.id)
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:success] = "プロフィールを編集しました"
     redirect_to user_path(@user.id)
    else
     render "edit"
    end
  end

  def search
    @content = params[:content]
    @users = User.search(@content)
  end
  # タイムライン
  def index
    @books = Book.where(user_id: [current_user.id, * current_user.following_ids]).order(created_at: :desc)
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="form">
      <%= form_with model:user, local:true do |f| %>
        <div class="modal-body">
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group">
            <%= f.label "プロフィール画像" %><br />
            <%= f.file_field :image %>
          </div>
          <div class="form-group">
            <%= f.label "ニックネーム" %><br />
            <%= f.text_field :name, autofocus: true, autocomplete: "name"%>
          </div>
          <div class="form-group">
            <%= f.label "紹介文" %><br />
            <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" , size: "60x7"%>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "変更を保存", class:"btn btn-success" %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="tl">
  <% if @books.empty? %>
    <div class="none">ニックネームで検索してフォローしてみよう</div>
  <% else %>
    <span id="back">
      <a href="#">
        <%= image_tag "arrow.png", class: "arrow" %>
      </a>
    </span>
    <% @books.each do |book| %>
      <div class="book-tl card mt-5 mb-5">
        <div class="book-user">
          <%= link_to user_path(book.user.id) do %>
            <% if book.user.image? %>
              <%= image_tag book.user.image.url, class: 'icon_mini' %><%= book.user.name %>
            <% else %>
              <%= image_tag "default.png", class: "icon_mini" %><%= book.user.name %>
            <% end %>
          <% end %>
          さんが本棚に登録しました
          <div class="text-right">
            <%= " (#{time_ago_in_words(book.created_at)}前)" %>
          </div>
        </div>
        <div class="book-box card">
          <div class="book-image">
            <%= link_to 'books/search?utf8=✓&keyword=' + (book.title + book.author) + '&commit=検索', data: {"turbolinks" => false} do %>
              <%= image_tag book.image, class: "bookhover" %>
             <% end %>
          </div>
          <div class="book-title">
            <%= book.title %>
          </div>
          <div class="book-author">
            <p style="color:#787878"><%= book.author %></p>
          </div>
          <div class="book-author">
            <% if book.rate.present? %>
              評価：<%= book.rate %>点
              <div id="star-rate-<%= book.id %>"></div>
              <script>
                $('#star-rate-<%= book.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= book.rate %>,
                });
              </script>
              <%= link_to "レビューを見る", book_path(book.id) %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/search.html.erb
<div class="search-page mt-5">
  <h1 class="mb-5"><i class="fas fa-search"></i>ニックネームでさがす</h1>
  <div class="search-form">
    <%= form_with url: users_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :content, placeholder: "ニックネームで検索" %>
      <%= f.submit '検索', class: "btn btn-primary" %>
    <% end %>
  </div>
<!--存在しないユーザーか空文字で検索した際に表示-->
  <% if !@content.nil? && (@content.empty? || @users.empty?) %>
    <p>お探しのユーザーは見つかりませんでした。</p>
<!--存在するユーザーを検索した際に表示-->
  <% elsif @users.present? %>
    <div class="container">
      <div class="row mt-5">
        <div class="col">
          <h2 class="text-center">検索結果</h2>
          <table class="table mt-5">
            <thead class="thead">
              <tr>
                <th>プロフィール画像</th>
                <th>ニックネーム</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <% if user.image? %>
                      <%= image_tag user.image.url, class: "icon_image" %>
                    <% else%>
                      <%= image_tag "default.png", class: "icon_image" %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to user_path(user) do %>
                      <%= user.name %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2 class="heading mt-5 mb-5"><i class="far fa-id-badge fa-fw"></i>プロフィール</h2>
  <div class="row">
    <div class="left-content col-md-6 col-xs-12">
      <% if @user.image? %>
        <%= image_tag @user.image.url, class: "icon_image" %><br>
      <% else %>
        <%= image_tag "default.png", class: "icon_image" %>
      <% end %>
      <div id="user_<%= @user.id %>">
        <div class="follow-count">
          <%= render "relationships/follow-count", user: @user %>
        </div>
        <% if current_user != @user %>
          <div class="follow-btn">
            <%= render "relationships/follow-btn", user: @user %>
          </div>
        <% end %>
      </div>
      <div class="chat">
        <% if current_user != @user %>
          <% if (current_user.following? @user) && (@user.following? current_user)  %>
            <%= link_to message_path(@user.id) do %>
              <i class="far fa-comments fa-2x my-gray"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="chat-index">
        <% if @user.id == current_user.id %>
          <%= link_to messages_path, class: "btn btn-info" do %>
            <i class="far fa-envelope fa-lg"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="right-content card col-md-6 col-xs-12">
      <div class="profile-name text-center mb-5 mt-5">
        <h5>ニックネーム</h5>
        <p><%= @user.name %></p>
      </div>
      <div class="profile-introduction text-center">
        <h5>紹介文</h5>
        <%= @user.introduction %>
      </div>
      <div class="profile-edit mt-5 text-right">
        <% if @user.id == current_user.id %>
          <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">
            プロフィール編集
          </button>
        <% end %>
      </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content" style="width:800px; margin-left: -150px;">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">プロフィール編集</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= render "users/edit", user: @user %>
            </div>
          </div>
        </div>
    </div>
  </div>
  <h2 class="mt-5 mb-5"><i class="fas fa-book fa-fw"></i>本棚</h2>
  <div class="bookshelf mb-5">
    <div class="row">
      <% @books.each do |book| %>
        <div class="books card col-lg-3 col-md-4 col-xs-12">
          <div id="bookshelf_<%= book.id %>">
            <%= link_to book_path(book.id) do %>
              <%= image_tag book.image, class: "bookhover" %><br />
            <% end %>
            タイトル:<%= book.title %><br>
            著者名:<%= book.author %><br>
            <% if @user.id == current_user.id %>
              <%= link_to "本棚から外す", book_path(book), method: :delete, remote: true, class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>