config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/users/search' => 'users#search'
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/books/search' => 'books#search'
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'message/:id' => 'messages#show', as: 'message'
  resources :messages, only: [:create, :index]
  delete 'notification/destroy_all' => 'notifications#destroy_all', as: 'notification'
  resources :notifications, only: :index
end

#書く順番気をつける

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  Copyright © 2021 MyBookshelf All Rights Reserved.
</footer>

app/views/layouts/_header.html.erb
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark p-4" style="background-color:#002129;">
      <a class="navbar-brand" href="/">MyBookshelf</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ml-auto">
        <!--ログインしている時に表示-->
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to user_path(current_user.id), class: 'nav-link active' do %>
                <i class="fas fa-book"></i>
                <h7>マイページ</h7>
              <% end %>
            </li>
            <li class="nav-item active">
              <%= link_to users_path, class: 'nav-link active' do %>
                <i class="fas fa-house-user"></i>
                <h7>タイムライン</h7>
              <% end %>
            </li>
            <li class="nav-item active">
              <%= link_to books_path, class: 'nav-link active' do %>
                <i class="fas fa-crown"></i>
                <h7>ランキング</h7>
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search"></i>
                <h7>さがす</h7>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to books_search_path, class: 'dropdown-item' do %>
                  <i class="fas fa-book-open"></i>
                  <h7>本をさがす</h7>
                <% end %>
                <%= link_to users_search_path, class: 'dropdown-item' do %>
                  <i class="fas fa-users"></i>
                  <h7>友達をさがす</h7>
                <% end %>
              </div>
            </li>
            <li class="nav-item active">
              <%= link_to notifications_path, class: 'nav-link active' do %>
                <% if unchecked_notifications.any? %>
                  <span class="fa-stack">
                    <i class= "fas fa-bell fa-lg"></i>
                    <i class= "fas fa-circle class: n-circle"></i>
                  </span>
                <% else %>
                  <i class= "fas fa-bell"></i>
                <% end %>
              <% end %>
            </li>
            <li class="nav-item active">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link active' do %>
                <i class="fas fa-sign-out-alt"></i>
                <h7>ログアウト</h7>
              <% end %>
            </li>
          <% else %>
          <!--ログインしていない時に表示-->
            <li class="nav-item active">
              <%= link_to about_path, class: 'nav-link active' do %>
                <h7>MyBookshelfとは？</h7>
              <% end %>
            </li>
            <li class="nav-item active">
              <%= link_to books_path, class: 'nav-link active' do %>
                <i class="fas fa-crown"></i>
                <h7>ランキング</h7>
              <% end %>
            </li>
            <li class="nav-item active">
              <%= link_to new_user_registration_path, class: 'nav-link active' do %>
                <i class="fas fa-user-plus"></i>
                <h7>新規登録</h7>
              <% end %>
            </li>
            <li class="nav-item active">
              <%= link_to new_user_session_path, class: 'nav-link active' do %>
                <i class="fas fa-sign-in-alt"></i>
                <h7>ログイン</h7>
              <% end %>
            </li>
          <% end %>
       </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&family=RocknRoll+One&display=swap" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <% key = "info" if key == "notice" %>
        <% key = "danger"  if key == "alert" %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>